spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/users/**
