spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/user_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

security:
  jwt:
    secret: ${JWT_SECRET:defaultSecret}
    expiration: 86400000 # 1 day

server:
  port: 0   # random available port
