spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/template_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 0   # random available port
